modbus: {baud: 19200, port: /dev/ttyUSB3, timeout: 10,
read_holding_registers_slaveids: [3,81,84],
read_holding_registers_count: [9,9,9],
read_holding_registers_start_address: [0,0,0],
read_input_registers_slaveids: [3,81,84],
read_input_registers_count: [9,9,9],
read_input_registers_start_address: [1000,1000,1000]}
