modbus: {baud: 19200, port: /dev/ttyO4, timeout: 10,
read_holding_registers_slaveids: [3,81,84],
read_holding_registers_count: [5,5,5],
read_holding_registers_start_address: [0,0,0],
read_input_registers_slaveids: [3,81,84],
read_input_registers_count: [8,8,8],
read_input_registers_start_address: [1000,1000,1000]}
