modbus: {baud: 19200, port: /dev/ttyO4, timeout: 1,
read_holding_registers_slaveids: [3,51,53],
read_holding_registers_count: [9,9,9],
read_holding_registers_start_address: [0,0,0],
read_input_registers_slaveids: [3,51,53],
read_input_registers_count: [9,10,10],
read_input_registers_start_address: [1000,1000,1000]}
